### PR TITLE
Fix submodule

### PR DESCRIPTION
**Pull request by lumikalt**
Put the styling of the homepage (`index.astro`) as a standalone file.
Add postcss support for minimizing the css output.
Fix & update the submodule.
Don't forget to update the submodule when there are new changes to it via `git submodule update --init --recursive`!
*huggg*

### CODE REVIEW

**Comment by lumikalt** [comment]
Oh! You might wanna make sure it runs pnpm or delete the pnpm lockfile and generate a new npm lockfile.

**Comment by lumikalt** [comment]
Idk why it's failing, can't check.
This last update added support for defining the `author` of a post, and also fixes my mistake with postcss from the last commit.

**Comment by initmd** [comment]
` ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with package.json`
hmmmm

**Comment by lumikalt** [comment]
Ah right, delete the pnpm-lock.yaml and run pnpm i (if you wish to use pnpm).
Otherwise, also delete that lockfile, and just run npm ci.

**Pull request closed without merging**
